jMonkeyEngine/sdk

jme3-code-check/src/com/jme3/gde/codecheck/hints/Bundle.properties, jme3-code-check/src/com/jme3/gde/codecheck/hints/InternalMethodHint.java, jme3-code-check/src/com/jme3/gde/codecheck/hints/ReadOnlyPrimitiveHint.java, jme3-code-check/src/com/jme3/gde/codecheck/hints/TempVarsHint.java, jme3-code-check/src/com/jme3/gde/codecheck/hints/UpdateHint.java
Moved strings from codechecks to a separate bundle as a part of preparation for a larger refactor of codechecks package.
=> Moved strings from codechecks to bundle.properties

jme3-core/src/com/jme3/gde/core/filters/impl/NewBloomFilterAction.java
Also the Bloom Filter Wizard does not support `SceneAndObjects` GlowMode. I was looking into how to fix it and figured out that it would require adding another JLabel into the menu and another `else if` into the `doCreateFilter()` function of `NewBloomFilterAction`. If no one fixes that I can maybe do it later.
=> Updated Bloom filter wizard's name

JME3TestsTemplate/nbproject/project.properties
My proposed fix for Issue #119 (JmeTests should specify native bullet, not jBullet). I haven't checked to see if the Android version of JmeTests has the same issue.
=> jbullet lib lacks jbullet.jar: use native bullet in JmeTests template

jme3-scenecomposer/src/com/jme3/gde/scenecomposer/gizmo/light/LightProbeGizmo.java
Setting the radius directly in the properties window on the right is still broken and doesn't work at all.
=> Fix LightProbe scaling by pressing S not working on jme version > 3.2

build_engine.sh, gradle.properties
Updated the display version of the sdk to 3.3 and added a git pull to build_engine.sh in case the engine/ folder is already present.
=> Version bump and build_engine.sh fixes for existing installs

jme3-ios/ios-data/templates/ios.properties
1. Exclusions:
java.nio.charset.Charset:
Otherwise you are limited to UTF-8 (and for example cannot use java.util.zip, because it uses ISO-8859-1)
For java.util.zip.Deflater:
java.util.zip.Deflater
java.io.FileNotFoundException
For reflection (IIRC nifty-gui and Java Annotations)
java.lang.reflect.Proxy
java.lang.reflect.InvocationHandler
For logging:
java.util.logging.ConsoleHandler
java.util.logging.FileHandler
java.util.logging.SimpleFormatter
java.util.logging.LogManager
For nifty-gui:
org.xmlpull.mxp1.MXParserFactory
2. Removed iOS version: just use link to the most recent version
This should reduce failing builds with new projects significantly!
=> iOS: add ProGuard exclusions

jme3-ios/ios-data/templates/project/jme-ios.xcodeproj/project.pbxproj, jme3-ios/ios-data/templates/project/jme-ios/jme-ios-Info.plist
The change contains the automatically migrated Xcode project. I tried to make the minimum changes, so that you have the chance to support older iOS/Xcode versions, too.
The minimum iOS version was automatically increased from 5.0 to 8.0.
(Therefore I have not provided a Launch Screen, which requires to increase iOS version to 9.0.)
Added important flags, otherwise the project will fail with errors:
-force_cpusubtype_ALL
ENABLE_BITCODE = NO
x86_64
Also removed the status bar and the MacOSX version number.
=> update project for Xcode 11.3.1

jme3-core/nbproject/project.xml
I could not build against the NB 12 without updating the Gradle lib dependencies, so here we go
=> Fix Gradle dependency to work with Netbeans 12

jme3-assetpack-support/src/META-INF/services/org.netbeans.spi.project.ProjectFactory, jme3-assetpack-support/src/com/jme3/gde/assetpack/project/AssetPackProject.java, jme3-assetpack-support/src/com/jme3/gde/assetpack/project/AssetPackProjectFactory.java, jme3-assetpack-support/src/com/jme3/gde/assetpack/project/AssetPackProjectLogicalView.java, jme3-core/src/META-INF/services/org.netbeans.spi.project.ProjectFactory, jme3-core/src/com/jme3/gde/core/codeless/CodelessProject.java, jme3-core/src/com/jme3/gde/core/codeless/CodelessProjectFactory.java
- Tidied up some related files
- Use annotations instead of the meta-inf (I understood this is the newer way, seems smarter to me, everything else is already with annotations)
- Implement ProjectFactory2 interface instead of the ProjectFactory
The newer interface speeds up things quite a bit. Now the project wont be loaded for just the preview, instead it is "instantly" recognized. In reality I doubt people have much of these projects laying around to see any speedup :) But hey, now this is up-to-date and ready for someone to copy paste...
I didn't find any place where the normal JME project is actually loaded up. I can see in the open projects dialog that it is recognized. When it is actually loaded, the project view shows the standard java icon instead of the JME icon seen in the open …
=> Projectfactory

jme3-ios/ios-data/templates/ios.properties, jme3-ios/ios-data/templates/project/jme-ios.xcodeproj/project.pbxproj, jme3-ios/ios-data/templates/project/jme-ios/Dummy.storyboard, jme3-ios/ios-data/templates/project/jme-ios/jmeAppDelegate.h, jme3-ios/ios-data/templates/project/jme-ios/jmeAppDelegate.m, jme3-ios/ios-data/templates/src/JmeAppHarness.java, jme3-ios/ios-data/templates/src/JmeIosGLES.m, jme3-ios/src/com/jme3/gde/ios/ios-targets.xml
List of changes:
- Fixed proguard rules.
- Added openGLES3 initialization.
- Implemented native code of missing methods of gles2.
- Implemented native code of gles3 methods.
- Forced compilation using java 8.
- Added Dummy.storyboard to be used as "Launch Screen File" in xcode to avoid bad aspect ratio and being able to use the whole screen and the proper resolution.
- Updated iPhone target to 9.0.
I'm just missing one detail, if I do need to replace also ./src/com/jme3/gde/ios/ios-data.zip or is it regenerated on SDK build?
Topic at hub: https://hub.jmonkeyengine.org/t/ios-improvements-including-gles3-0/44332
** This PR needs the related engine PR: https://github.com/jMonkeyEngine/jmonkeyengine/pull/1473
=> Ios gl3 and some improvements

jme3-materialeditor/src/com/jme3/gde/materialdefinition/editor/ShaderNodePanel.java
This fix is includes in my behemoth PR as well, although refactoring makes it differ slightly. I figure it's better if I can produce a couple of smaller PR's, then merge them (and deal with the conflicts) before someone tackles the big PR.
=> fixes #339 Attribute nodes are expected to be named "Attr"

jme3-materialeditor/src/com/jme3/gde/materialdefinition/fileStructure/DefinesBlock.java, jme3-materialeditor/src/com/jme3/gde/materialdefinition/fileStructure/TechniqueBlock.java, jme3-materialeditor/src/com/jme3/gde/materialdefinition/fileStructure/UberStatement.java, jme3-materialeditor/src/com/jme3/gde/materialdefinition/fileStructure/leaves/DefineBlock.java, jme3-materialeditor/src/com/jme3/gde/materialdefinition/fileStructure/leaves/LeafStatement.java
=> adding block statements to Technique to retain any added Defines

jdks/download-jdks.sh
Just a simple JDK update. Scripts still work. I use this version myself and it has been out for some time now.
=> Get the latest JDK 11

BasicGameTemplate/nbproject/project.properties
When creating a BasicGame in the SDK with the Ant build system it was still referencing the removed jme-bullet.jar.
I changed it to rather point to the jbullet implementation of the physics engine.
Also updated the javac.source and javac.target to JAVA 11.
=> Removed reference to old jme-bullet.jar and point to jbullet

jme3-templates/src/com/jme3/gde/templates/Bundle.properties, jme3-templates/src/com/jme3/gde/templates/basic/BasicGameDescription.html, jme3-templates/src/com/jme3/gde/templates/gradledesktop/GradleDesktopGameDescription.html
This fixes the error stack appearing in the IDE logs (#363). Also unifies the template descriptions, also with the ones already offered by NB itself. Added a bit more description and a recommendation to Grade.
=> Unify and fix the game template strings

jme3-core/src/com/jme3/gde/core/assets/AssetsLookupProvider.java
Fixes (hopefully) #379 
Problem was caused by newer underlying version of Netbeans Gradle tooling returning the Asset sub-project name as `:assets` rather than `assets`
=> #379 - Fix 'File is not part of a jME project'

build.gradle
This fixes #368, fixes #283.
Mark the examplelibs configuration to only contain itself, since we actually ship the dependencies to the created project. This library is used only to copy its sources to the project template.
What do you think @MeFisto94 ?
=> Mark examplelibs as non-transitive, enable javadoc and sources for all

jme3-core/src/com/jme3/gde/core/assets/AssetsLookupProvider.java
Partially fixes #382.
What is very strange is that when the Project is first created, and loaded by NB, the Asset sub-project name is returned by the Gradle API as "assets".  
When the Project is subsequently loaded (e.g. on SDK restart) the Asset sub-project name is returned as ":assets"
🤷
=> Accept with 'assets' or ':assets' as Gradle Assets sub-project name

jme3-materialeditor/src/com/jme3/gde/materials/EditableMaterialFile.java
Fixes #336 Some noise here due to me removing some warnings and formatting the file. Check the comment for the change that matters.
It actually changes the "source" as well. But I guess that is more in line with WYSIWYG, after all.
=> Fixes_#336_Default_values_from_MatDef

jme3-core/src/com/jme3/gde/core/scene/SceneApplication.java, jme3-core/src/com/jme3/gde/core/scene/state/NormalViewState.java, jme3-core/src/com/jme3/gde/core/sceneviewer/SceneViewerTopComponent.form, jme3-core/src/com/jme3/gde/core/sceneviewer/SceneViewerTopComponent.java
This is using a temporary icon. I'll fix that once https://github.com/jMonkeyEngine/sdk/pull/385) is merged, rather than building this on top of the other branch.
Normal length could be debated. Currently it's 0.2 units.
Fixes #200
=> NormalViewState appstate and hook up for SceneViewer

build.gradle, jme3-project-testdata/src/com/jme3/gde/project/testdata/jme3-test-data.xml
build.gradle might not be required, but i noticed a path that wasn't updated. the fix is in jme-test-data.xml
=> fix JmeTests project requirement

jme3-core/src/com/jme3/gde/core/assets/ExternalChangeScanner.java
New feature:
Remember this option for ExternalChangeScanner. Fixes #343 
Bug fixes:
Exception for not executing on awt thread
Handling closing window without selecting an option
=> ExternalChangeScanner bug fixes and improvement

jme3-dark-laf/nbproject/project.xml, jme3-dark-laf/src/org/jme3/netbeans/plaf/darkmonkey/Installer.java, jme3-welcome-screen/src/com/jme3/gde/welcome/GradPanel.java
DarkMonkey has quite a few visual bugs / inconsistencies in modern Netbeans.  This is a proposal to set FlatLaf dark as the default Look and Feel, but keep the DarkMonkey editor colours.  DarkMonkey is still installed, so available to anyone who wants to switch back to it.
The gradient for the Welcome screen is updated, so if a Dark theme is detected, it will be more fitting / readable.
=> Set FlatLaf Dark as default Look and Feel

jme3-core/src/com/jme3/gde/core/assets/ProjectAssetManager.java, jme3-core/src/com/jme3/gde/core/assets/actions/UpdateProjectAssetManagerAfterBuild.java
Hopefully goes some way to fixing #373 
A couple of bits that could use further refinement:
1. When you first create a new Gradle JME project, NB will prompt you for a priming build - due to changes in NB's Gradle API in latest version, because our Gradle project is created by unziping a file rather than using NB's Gradle API, it is untrusted at this stage and the priming build doesn't run.  This means the user need to run Gradle build again manually before resources will be loaded off the Gradle dependencies - the real fix for this needs to be in the Gradle template.
2. Hard coded to use look at the `main` sourceset - if user has defined custom sourcesets in their `build.gradle` these will get ignored
Could do with some testing, inc. making sure nothing in Ant based projects is now …
=> Improve ProjectAssetManager's Gradle support

jme3-dark-laf/src/org/jme3/netbeans/plaf/darkmonkey/Installer.java
Fixes #457 
In order to get FlatLaf Dark to work "first time" without needing an IDE reset to fix the colours of the Option header bar etc. I had to move setting the default LaF from the static initialisation block to the `validate()` lifecycle hook.
Setting the Editor profile doesn't work in the `validate()` block though (too early in IDE startup), so I moved it to the `restored()` lifecycle hook which gets called later - completely missing that it was no longer behind an `if` so Editor profile was getting set to Dark Monkey colours every time the IDE started.
This fixes that by setting a static boolean so that we only set the Editor profile if we are also setting the default LaF (i.e. the first time we load the darkmonkey module).
=> Do not overwrite Editor Profile on every load

jme3-core/src/com/jme3/gde/core/assets/ProjectAssetManager.java
Not sure if the Ant projects should just continue to the few lines after the seemingly Gradle specific thing... But Ant project assets seem to work ok (shows the yellow icon and can open to scene explorer). Having Ant projects open, this resulted in nasty NPE.
=> Fix NPE and reduce nesting

build.gradle
At least I get a build error if I don't switch the mavenCentral as first repo. com.github.stephengold:j-ogg-all is nowadays hosted in Maven central. And removed from other sources. There is simply a message to use Maven central. This fixes it for me.
```
Full Version: 3.5-2321 |  
-- | --
<span class="ConsoleLogItem__text ConsoleLogItem__text--gradle_failure">BUILD FAILED</span><span class="ConsoleLogItem__text ConsoleLogItem__text--normal"> in 6s</span>
</body>
</html>Full Version: 3.5-2321	
POM Version: 3.5.2-SNAPSHOT	
NBM Revision: 2321	
NBM UC Suffix: nightly/3.5/plugins	
FAILURE: Build failed with an exception.	
* Where:	
Build file 'C:\Users\Toni\Documents\ToniArts\sdk\build.gradle' line: 133	
* What went wrong:	
A problem occurred evaluating root project 'sdk'.	
> Could not resolve …
```
=> Update some stephengold libraries and make mavenCentral the first place

build.gradle, gradle.properties
Not sure if this is a great solution, but it seems to work when i build locally.
=> update to 3.6.0-stable and ignore META-INF entry when making project.xml

license-jme.txt, licenses-sdk.txt
Resolves #483 
-jme-txt is used by the installer. At least according to Netbeans properties on the project. Did not test it. Also changed the other license at the same time.
=> Update license years

jme3-templates/src/com/jme3/gde/templates/gradledesktop/GradleDesktopGameJMEVersionPanelVisual.java
Fixes #482 
Just refresh the patch notes, basically when the panel is displayed.
=> Make sure we refresh the patch notes for jME version

jme3-scenecomposer/src/com/jme3/gde/scenecomposer/SceneComposerTopComponent.java
=> Fixes reported issue when changing camera near plane.

.github/workflows/release.yml, build.xml, jdks/download-jdks.sh
pack200 was removed with Java 14. We are on Java 17. No-go. I did not test this but looks like the Windows installer falls to using the bundled JDK (17) to try unpack pack200 and fails. I have no idea why it works on Linux.
=> Fix Windows installer

jme3-core/src/com/jme3/gde/core/scene/controller/SceneToolController.java
Changes Scene Composer grid from 20 lines x 20 lines (19 squares x 19 squares) to 21 lines x 21 lines (20 squares x 20 squares) so it is symmetrical.
Fixes #516 
**Before**:
**After**:
=> Make Scene Composer grid symmetrical

jme3-materialeditor/src/com/jme3/gde/materials/multiview/MaterialEditorTopComponent.java, jme3-materialeditor/src/com/jme3/gde/shadernodedefinition/wizard/SNDefVisualPanel2.form, jme3-materialeditor/src/com/jme3/gde/shadernodedefinition/wizard/SNDefVisualPanel2.java
Hope I didn't miss anything. I feel like those values should be available somewhere, but don't know where. 
(Adding the default "float" to make the row visible. Very confusing otherwise and you tend to click on "Add" several times)
Fixes #324
=> #324 - changes VarType to JComboBox with hardcoded values for Shader Node wizard

.github/workflows/release.yml, build.xml, jdks/download-jdks.sh
Resolves #558 
Not build by default and not build by our release build. Downloading the JDKs doesn't get the parameters what to build, so enabling x86 build doesn't work anymore straight as corresponding JDK is missing. I think it is better this way, much lighter for everyone. x86 isn't coming back really...
=> Disable Windows x86 by default

jme3-core/src/com/jme3/gde/core/sceneexplorer/nodes/animation/JmeAnimClip.java, jme3-core/src/com/jme3/gde/core/sceneexplorer/nodes/animation/JmeAnimClipChildren.java, jme3-core/src/com/jme3/gde/core/sceneexplorer/nodes/animation/JmeAnimComposer.java
=> fix stopping and removing animclip when deleting them

jme3-core/src/com/jme3/gde/core/sceneexplorer/nodes/JmeCharacterControl.java
Had to lose couple of fields. In Minie, these fields have a getter that takes in a parameter. This is not really supported at all.
Resolves #587
=> Update CharacterControl to be compatible with Minie

jdks/download-jdks.sh
Resolves #595 
Basically now all releases will get the freshest available JDK. We no longer have the exact version info in the script but I don't think that matters. Locally I just wipe out everything before running the script. And the release is always created in a new empty environment. So the exact version in paths doesn't matter.
=> Always get the latest JDK version

jme3-materialeditor/src/com/jme3/gde/materials/multiview/MaterialEditorTopComponent.java
ProjectAssetManager gathers matdefs from all dependencies, so duplicates are expected.
I first tried to convert it to a Set and back, but in the end, I think this is the simplest solution.
Fixes #597
=> Issue 597 - Avoid duplicates in matdef list

jme3-core/src/com/jme3/gde/core/sceneexplorer/nodes/JmeControl.java, jme3-core/src/com/jme3/gde/core/sceneexplorer/nodes/animation/JmeAnimClip.java, jme3-core/src/com/jme3/gde/core/sceneexplorer/nodes/animation/JmeAnimComposer.java, jme3-core/src/com/jme3/gde/core/sceneexplorer/nodes/animation/JmeAnimComposerChildren.java, jme3-core/src/com/jme3/gde/core/sceneexplorer/nodes/animation/JmeAnimLayer.java, jme3-core/src/com/jme3/gde/core/sceneexplorer/nodes/animation/JmeBone.java, jme3-core/src/com/jme3/gde/core/sceneexplorer/nodes/animation/JmeBoneChildren.java, jme3-core/src/com/jme3/gde/core/sceneexplorer/nodes/animation/JmeJoint.java, jme3-core/src/com/jme3/gde/core/sceneexplorer/nodes/animation/JmeSkeletonControl.java
One little annoying thing... They can't be saved!
https://youtu.be/-hgwB6x-11s 
I really tried getting AnimClips and AnimLayers into two different sub nodes, but it didn't work out.
=> Create AnimLayers in the SceneComposer and play animations

jme3-assetbrowser/src/com/jme3/gde/assetbrowser/AssetBrowser.java, jme3-core/src/com/jme3/gde/core/assets/ProjectAssetManager.java
Fixes #606
Replacing LinkedList with TreeSet in ProjectAssetManager. Hopefully nothing goes wrong..
Edit: I've done some testing around the material editor and scene composer. Didn't notice anything out of the ordinary.
=> Issue-606. replace String list with TreeSet

jme3-templates/src/com/jme3/gde/templates/files/freemarker/build.gradle.ftl
Duh, we ship Java 21. The templates need to use 21 or the user has to get Java 17. Not good.
=> Gradle template to use Java 21

gradle.properties, jme3-blender/src/com/jme3/gde/blender/GltfExtrasLoader.java
jME 3.7 stable.
Beautiful try catch code with the new JSON abstraction
=> Feature/jme 3.7 stable

build.gradle
I did test the jME tests with Minie and I got Javadoc & Sources too. Looks like if you want to run jME tests with Minie, there is one function to remove and RigidBodyControl needs some field accesses replaced with getters.
I don't know if there is some 3.7 compatibility issues with the old libraries but at least now there should not be.
=> Update Stephen's library versions

jme3-core/src/com/jme3/gde/core/appstates/NewAppStateVisualPanel1.java
Ref: https://hub.jmonkeyengine.org/t/help-needed-with-j3o-sdk-functions/48036
=> fix AppStateExplorer not finding AppStates extending BaseAppState

build.gradle, jme3-core/src/com/jme3/gde/core/assets/actions/MergeAnimationsAction.java, jme3-scenecomposer/src/com/jme3/gde/scenecomposer/Bundle.properties, jme3-scenecomposer/src/com/jme3/gde/scenecomposer/layer.xml
Based on this discussion: https://hub.jmonkeyengine.org/t/importing-model-and-animations-from-unreal/48015
This includes Wes in the core base libs now. But I don't see it as a bad thing. Might find other uses for it now it's there.
=> Merge animations actions

jme3-glsl-highlighter/src/com/jme3/gde/glsl/highlighter/lexer/GlslLexer.java
Hmm, there was this empty section that should have maybe been an early exit? It looks to highlight ok, So it is probably this simple. I really want to optimize the [GlslKeywordLibrary.java](https://github.com/jMonkeyEngine/sdk/blob/master/jme3-glsl-highlighter/src/com/jme3/gde/glsl/highlighter/lexer/GlslKeywordLibrary.java) but better do that in another PR and issue.
Resolves #632
=> Fix NPE on GlslLexer

BasicGameTemplate/nbproject/project.properties, JME3TestsTemplate/nbproject/project.properties, build.gradle
=> Also include the JSON GSON implementation for gLTF model loading

jme3-scenecomposer/src/com/jme3/gde/scenecomposer/SceneEditTool.java
Not sure what has happened here, must be a regression of some sort.
I noticed when creating a skybox (during) that it threw an error. This also occurs when selecting a node which contains a skybox.
The cause is that the skybox has an infinite bound (naturally), this is propagated to the node, which tries to set the tool marker scale to be the same as the bounds of the node. This throws an assert error about inifite scale.
I've limited the scale to 100, and it will set it to 1 if it exceeds that. This is arbitrary.
=> don't allow bounding scale for marker to be too large

jme3-terrain-editor/src/com/jme3/gde/terraineditor/TerrainEditorController.java
=> Issue #651 save asset node in TerrainEditorController
