jme3-gui/src/com/jme3/gde/gui/templates/NiftyGui.xml

This enables auto completion in the xml editor again.

Fix nifty schema location

---

BasicGameTemplate/nbproject/project.properties

Fixes #94, swithced to java 7 since java 8 isnt supported on android.

Fix source version

---

JME3TestsTemplateAndroid/nbproject/project.properties

Sorry for a separate PR, but I'm working from github's web interface for file editing which doesn't allow pushing edits to the same branch, but creates a new one every time.

Android fix for #114

---

jme3-scenecomposer/src/com/jme3/gde/scenecomposer/gizmo/light/DirectionalLightGizmo.java
jme3-scenecomposer/src/com/jme3/gde/scenecomposer/gizmo/light/LightGizmoFactory.java

Fixed DirectionalLight gizmo direction

---

build.gradle

Add the Minie Physics Library to the set of built-in Libraries available

---

build.gradle

Minie depends on Heart, so we'd better include that library. Wes is the animation editing library, which might prove useful. Additional information at the JmonkeyStore:
+ Heart: https://jmonkeystore.com/e534fc1e-5b78-46b7-a831-d5d40cbd9dcd
+ Wes: https://jmonkeystore.com/15054f52-c439-4bfb-9a73-80260b486333

add 2 optlibs: Heart v5.0 and Wes v0.4.8

---

jme3-ios/ios-data/templates/project/jme-ios/jmeAppDelegate.m
jme3-ios/ios-data/templates/project/jme-ios/logging.properties

- jmeAppDelegate.m: without the scale factor (which is device specific) you'll hit the wrong location
- jmeAppDelegate.m: the cast (long) is required for the simulator
- logging.properties: added comments how to turn on logging, this can be really helpful

fix iOS touch: added scale factor

---

jme3-ios/ios-data/templates/project/jme-ios/jmeAppDelegate.m

The current implementation only forwards one touch. Now I iterate through the list.
I also use a pointer ID instead of 0, so that it's possible to distinct between the fingers.
The cast to (jint) is optional I think.
The length of the list indicates how many fingers started the touch, so now we can detect gestures. (Which requires custom code, of course.)

Add multi-touch support for iOS

---

jme3-core/src/com/jme3/gde/core/scene/FakeApplication.java

I was profiling the SDK and it annoyed me that this didn't have any name this thread. Basically this does nothing more than name the thread created by the pool. The pool type I changed to what I think is more what we wanted here.

Name the fake application update thread

---

jme3-assetpack-support/src/com/jme3/gde/assetpack/actions/AddToProjectAction.java
jme3-core/src/com/jme3/gde/core/assets/AssetDataObject.java

In kinda relation to https://github.com/jMonkeyEngine/jmonkeyengine/pull/1434... Also speed up the SDK model writes. The FileObject returns plain FilterOutputStream.

Use BufferedOutputStream

---

jme3-scenecomposer/src/com/jme3/gde/scenecomposer/gizmo/light/DirectionalLightGizmo.java

gizmo still flickers a bit, but at least rotation is consistent. #206

fixes annoying directionallight rotation

---

jme3-codepalette/src/com/jme3/gde/codepalette/layer.xml
jme3-core/src/com/jme3/gde/core/util/notify/NotifyUtil.java

I seemed to have some changes done awhile ago. Might as well push them. Just some cleaning up. Switches the use of timer to something hopefully better. Seems to work and I think it is appropriate to use the NB common thread pool. The Audio device pausing message is one that pops up for me and that I used to test this.
https://netbeans.apache.org/wiki/DevFaqRequestProcessor.asciidoc

Misc fixes

---

jme3-core/src/com/jme3/gde/core/assets/ExternalChangeScanner.java
jme3-core/src/com/jme3/gde/core/util/SpatialUtil.java

updates material. null check if mesh names have changed

---

jme3-core/src/com/jme3/gde/core/scene/controller/SceneToolController.java
jme3-scenecomposer/src/com/jme3/gde/scenecomposer/Bundle.properties
jme3-scenecomposer/src/com/jme3/gde/scenecomposer/SceneComposerTopComponent.form
jme3-scenecomposer/src/com/jme3/gde/scenecomposer/SceneComposerTopComponent.java

Might seem like a minor thing, but sometimes you want to position things in code and currently you need to create a new Node and drag it around until it's where you want it. Now you can just point wherever and see the position.

making the cursor arrow more usable, show position in panel.

---

jdks/download-jdks.sh

AdoptOpenJDK is nomore :( Change to Temurin and (almost) latest Java 11

Jdk script

---

jme3-materialeditor/src/com/jme3/gde/materialdefinition/fileStructure/InputMappingsBlock.java
jme3-materialeditor/src/com/jme3/gde/materialdefinition/fileStructure/ShaderNodeBlock.java
jme3-materialeditor/src/com/jme3/gde/materialdefinition/fileStructure/ShaderNodesBlock.java

I think this puts the shader nodes in order, at least when edited. It won't fix everything retroactively. Should solve  #335

sorting for shadernodeblock.

---

version.gradle

Travis tag doesn't exist anymore, the alternative doesn't actually work. See if we can just inject the tag name from GH actions

Try to get the tag name from properties

---

jme3-core/src/com/jme3/gde/core/sceneexplorer/nodes/JmeLightProbeProgressHandler.java
jme3-materialeditor/src/com/jme3/gde/materialdefinition/EditableMatDefFile.java

More of a work around I guess. I found a lot of hits for the specific error in netbeans bug list itself, but no solution (links were too old). But switching to "indeterminate" (no percentage progress bar) seems to work. I've generated around 50 light probes without the issue appearing (used to happen within the first 3 before). I've also generated a couple of "high quality bakes" which take much longer.

#175 lightprobe process fails

---

jme3-materialeditor/src/com/jme3/gde/materialdefinition/dialog/AddMaterialParameterDialog.form
jme3-materialeditor/src/com/jme3/gde/materialdefinition/dialog/AddMaterialParameterDialog.java

Mostly renaming. Juicy stuff at row 176
Fixes #399

#399 Enforcing name to be at least one character

---

jdks/download-jdks.sh

New JDK version, this is already available. I recon it is the final build.

Pick up new JDK version

---

jme3-scenecomposer/src/com/jme3/gde/scenecomposer/icons/add.svg

I can't verify the difference, but it should be absolute center now.

centering add icon

---

jme3-core/src/com/jme3/gde/core/icons/IconList.java

Fixes #424 
Also affected Anim clips

correct icon name

---

jme3-materialeditor/src/com/jme3/gde/materials/EditableMaterialFile.java

This seems to fix #430 as well as retain #336. I want to test this some more before merging.

preliminary fix for #430

---

.github/workflows/release.yml

changing back to previous settings

reverting workflow change

---

jme3-core/src/com/jme3/gde/core/icons/IconList.java

correct name for particle emitter icon

---

jdks/download-jdks.sh

Latest JDK 17

---

jme3-templates/src/com/jme3/gde/templates/files/patchnotes/361-stable.html
jme3-templates/src/com/jme3/gde/templates/gradledesktop/options/JMEVersion.java

Add jME 3.6.1 to known versions

---

nbproject/project.properties

Open module to allow drag & drop in code editor

---

build.gradle

To help steer users toward Paul Speed's libraries.

add 5 optional libraries from com.simsilica

---

jme3-materialeditor/nbproject/project.xml
jme3-materialeditor/test/unit/src/com/jme3/gde/materials/multiview/widgets/TexturePanelTest.java

I think this got deleted in the asset browser merge

add back unit test that has gone missing

---

jdks/download-jdks.sh

Get new Java 17 version

---

jme3-core/src/com/jme3/gde/core/sceneexplorer/nodes/JmeVehicleWheel.java

remove fields not existing in Minie

---

build.gradle

Loaded the Vehicle Creator as a test and ran a simulation.

Update Minie to 8.0.0 and Heart to 9.0.0

---

jme3-autodesk/nbproject/suite.properties

Add missing file

---

jme3-core/src/com/jme3/gde/core/sceneexplorer/nodes/JmeVehicleWheel.java

Fix https://github.com/jMonkeyEngine/sdk/issues/589

Fix JmeVehicleWheel: wrong Sheet.Set name

---

jme3-assetpack-support/src/com/jme3/gde/assetpack/browser/properties/SelectionPropertyEditor.java

Hi. I simple corrected incorrect assignment variable.

Fix incorrect assignment

---

jme3-core/src/com/jme3/gde/core/appstates/NewAppStateVisualPanel1.java
jme3-core/src/com/jme3/gde/core/assets/ProjectAssetManager.java
jme3-core/src/com/jme3/gde/core/sceneexplorer/nodes/actions/impl/NewCustomControlVisualPanel1.java

Dunno why Gradle projects specifically skipped folders but that is how I at least got the compiled classes going.
Closes #640

Fix adding custom controls and app states to scenes in Gradle projects

---

jme3-materialeditor/src/com/jme3/gde/materials/MaterialPropertyEditor.java

i entirely blame the logs for being so hard to read.

fix material editor incompatibility
